#!/bin/sh
# graft-lodoros.sh — turn a fresh MinUI fork clone into the LodorOS fork repo.
# Applies LodorOS's launcher + paks + release tooling ON TOP of MinUI's base history,
# committed as lodordev. The engine is NOT here (separate lodordev/lodor repo).
#
#   graft-lodoros.sh <minui-fork-clone> <lodor-mono> <public-readme>
#
# Run this AFTER you fork shauninman/MinUI on GitHub and clone your fork — it preserves
# MinUI's history + the "forked from" relationship, then layers LodorOS on top.
set -eu
MINUI="${1:?usage: graft-lodoros.sh <minui-fork-clone> <lodor-mono> <public-readme>}"
MONO="${2:?usage: graft-lodoros.sh <minui-fork-clone> <lodor-mono> <public-readme>}"
README="${3:?usage: graft-lodoros.sh <minui-fork-clone> <lodor-mono> <public-readme>}"
[ -d "$MINUI/.git" ] || { echo "FATAL: $MINUI is not a git repo — fork+clone MinUI first" >&2; exit 2; }

cd "$MINUI"
echo ">> overlay LodorOS launcher/minarch source over MinUI's workspace/ (the fork diff)"
rm -rf workspace
cp -a "$MONO/lodoros/workspace" workspace

echo ">> add LodorOS paks, heavy-shim paks, config/wifi examples"
cp -a "$MONO/lodoros/paks" paks
cp -a "$MONO/lodoros/emus-h700" emus-h700
cp -a "$MONO/lodoros/config.json.example" config.json.example 2>/dev/null || true
cp -a "$MONO/lodoros/wifi.txt.example"    wifi.txt.example    2>/dev/null || true

echo ">> add LodorOS release tooling + config contract"
cp -a "$MONO/release"  release
cp -a "$MONO/contract" contract

echo ">> docs: public README, hybrid LICENSE, CREDITS"
cp -a "$README"              README.md
cp -a "$MONO/LICENSE"        LICENSE
cp -a "$MONO/lodoros/CREDITS.md" CREDITS.md

echo ">> drop internal / non-fork files (MinUI todo, our ledger, engine)"
rm -f ledger.md todo.txt
rm -rf engine integrations   # engine = its own repo; integrations = separate products
rm -rf release/out           # build artifacts never belong in public source (regenerated by release/build-public.sh)

git add -A
git -c user.name=lodordev -c user.email=dev@lodor.local commit -q -m "LodorOS: RomM thin-client, forked from MinUI

Turns a MinUI-family handheld into a thin client for a self-hosted RomM server:
whole-library offline browsing, download-on-launch with hash verification, two-way
save sync, and private server access (Tailscale / Cloudflare Access). The launcher is
forked from MinUI (Shaun Inman, used with permission); the CGO-free RomM sync engine is
the separate lodordev/lodor module, bundled at build time."
echo "== grafted =="
git log --oneline -3
echo "== top-level of the fork repo =="
ls -1 | grep -vE "^\.git$"
