#!/bin/sh
# up.sh — bring up the disposable test RomM, seed a tiny fixture library, and wait until
# the fixtures are visible over REST. Prints the base URL + admin credentials on success.
# Companion: down.sh (removes containers AND volumes — see the valkey note below).
#
#   sh release/test-romm/up.sh          # idempotent; safe to re-run
#
# Hermetic by construction: no metadata-provider keys (zero egress), port on 127.0.0.1 only.
#
# LAN MODE (opt-in, NEVER the default):
#   ROMM_TEST_LAN=1 sh release/test-romm/up.sh
# publishes on <your-lan-ip>:8998 INSTEAD of loopback. It exists
# SOLELY for the macOS AVD e2e leg (integrations/android/test/avd-e2e.sh), whose
# emulator must reach this instance across the LAN. Tear down after the run — either
# down.sh, or re-run up.sh without ROMM_TEST_LAN to snap the bind back to loopback
# (the port change alone recreates the container; volumes/state survive).
# Set the LAN IP with ROMM_TEST_LAN_IP; LAN mode refuses to start without it.
#
# HOW SCANNING WORKS HERE (RomM 5.0.0, learned the hard way 2026-07-22):
#  - `scan_library` is manual_run:false — the REST task API refuses it; real scans are
#    UI/socket.io-only. So the compose file enables the SCHEDULED rescan with cron
#    `* * * * *`: the library rescans within ~60s of boot, continuously. Fixtures are tiny.
#  - Scheduler registrations live in valkey, whose data sits in a MOUNTED VOLUME and
#    SURVIVES container recreation. If you change scan/cron config in compose.yml, a
#    plain `up -d` will NOT apply it — run down.sh (which nukes volumes/) first.
#  - Unauthenticated first-boot POSTs need the CSRF dance: cookie from any GET, echoed
#    back as X-CSRFToken. First admin = POST /api/users (username/password/EMAIL/role).
set -eu
HERE=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
ADMIN_USER=testadmin
ADMIN_PASS=testadmin-pw

# Bind selection: loopback default; LAN only when explicitly asked for (AVD e2e leg).
LAN_IP=${ROMM_TEST_LAN_IP:-}
if [ "${ROMM_TEST_LAN:-0}" = "1" ]; then
  # LAN mode has no default IP on purpose: the previous default hard-coded one host's
  # address. Callers must name the address they want to publish on.
  [ -n "$LAN_IP" ] || { echo "FATAL: ROMM_TEST_LAN=1 needs ROMM_TEST_LAN_IP=<this host's LAN IP>" >&2; exit 2; }
  export ROMM_TEST_BIND="$LAN_IP"
  BASE="http://$LAN_IP:8998"
  echo ">> LAN MODE: binding $LAN_IP:8998 (macOS AVD e2e only — tear down after)"
else
  export ROMM_TEST_BIND=127.0.0.1
  BASE=http://127.0.0.1:8998
fi

# fixture library: generated bytes, never real ROMs — platform dirs use RomM fs slugs.
# gamegear + psp are NOT decoration: the muOS integ harness's LIVE leg downloads a Sega
# Game Gear stub through the launch override (the engine maps gamegear -> "Sega Game Gear"
# / Genesis Plus GX) and asserts the STANDALONE Sony PlayStation Portable folder is left
# un-overridden. Without both, that leg either fails on a missing stub or passes vacuously
# against an absent folder — which is why it only ever ran against a live personal server
# (2026-07-25). Keep them.
mkdir -p "$HERE/library/roms/gba" "$HERE/library/roms/nes" \
         "$HERE/library/roms/gamegear" "$HERE/library/roms/psp" "$HERE/volumes"
[ -f "$HERE/library/roms/gba/lodor-fixture-alpha.gba" ] || \
  dd if=/dev/urandom of="$HERE/library/roms/gba/lodor-fixture-alpha.gba" bs=1024 count=64 2>/dev/null
[ -f "$HERE/library/roms/gba/lodor-fixture-beta.gba" ] || \
  dd if=/dev/urandom of="$HERE/library/roms/gba/lodor-fixture-beta.gba" bs=1024 count=64 2>/dev/null
[ -f "$HERE/library/roms/nes/lodor-fixture-gamma.nes" ] || \
  dd if=/dev/urandom of="$HERE/library/roms/nes/lodor-fixture-gamma.nes" bs=1024 count=40 2>/dev/null
[ -f "$HERE/library/roms/gamegear/lodor-fixture-delta.gg" ] || \
  dd if=/dev/urandom of="$HERE/library/roms/gamegear/lodor-fixture-delta.gg" bs=1024 count=32 2>/dev/null
[ -f "$HERE/library/roms/psp/lodor-fixture-epsilon.iso" ] || \
  dd if=/dev/urandom of="$HERE/library/roms/psp/lodor-fixture-epsilon.iso" bs=1024 count=48 2>/dev/null

COMPOSE="docker compose"; docker compose version >/dev/null 2>&1 || COMPOSE=docker-compose
export ROMM_TEST_SECRET=$(head -c32 /dev/urandom | sha256sum | cut -c1-64)
$COMPOSE -f "$HERE/compose.yml" up -d

echo ">> waiting for RomM heartbeat..."
i=0; until curl -sf "$BASE/api/heartbeat" >/dev/null 2>&1; do
  i=$((i+1)); [ "$i" -gt 100 ] && { echo "FATAL: no heartbeat after 200s"; exit 1; }; sleep 2
done

# first-boot admin via the CSRF dance; idempotent (non-201 = already exists, verified below)
J=$(mktemp); trap 'rm -f "$J"' EXIT
curl -s -c "$J" "$BASE/api/heartbeat" >/dev/null
TOK=$(awk '/csrftoken/ {print $NF}' "$J")
curl -s -o /dev/null -b "$J" -X POST "$BASE/api/users" \
  -H "Content-Type: application/json" -H "X-CSRFToken: $TOK" \
  -d "{\"username\":\"$ADMIN_USER\",\"password\":\"$ADMIN_PASS\",\"email\":\"$ADMIN_USER@lodor.test\",\"role\":\"admin\"}" || true
curl -sf -u "$ADMIN_USER:$ADMIN_PASS" "$BASE/api/users/me" >/dev/null \
  || { echo "FATAL: admin login failed after create attempt"; exit 1; }

echo ">> waiting for the scheduled rescan to surface the fixtures (cron: every minute)..."
i=0; while :; do
  n=$(curl -sf -u "$ADMIN_USER:$ADMIN_PASS" "$BASE/api/roms?limit=20" 2>/dev/null \
      | python3 -c "import json,sys;d=json.load(sys.stdin);print(len(d) if isinstance(d,list) else len(d.get('items',[])))" 2>/dev/null || echo 0)
  [ "${n:-0}" -ge 5 ] && break
  i=$((i+1)); [ "$i" -gt 60 ] && { echo "FATAL: fixtures not visible after 180s (have: ${n:-0}/5). Stale valkey state? Run down.sh and retry."; exit 1; }
  sleep 3
done
echo "test-romm READY: $BASE  (user: $ADMIN_USER / $ADMIN_PASS, $n roms)"
[ "${ROMM_TEST_LAN:-0}" = "1" ] && echo "REMINDER: LAN-bound. After the e2e run: re-run up.sh without ROMM_TEST_LAN (or down.sh) to restore loopback."
exit 0
